/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.twosquirrels.donguri

import kotlin.test.Test
import kotlin.test.assertNotNull

class DonguriTest {
    /*@Test fun testName() {
        val classUnderTest = Donguri()
        // test
    }*/
}
