name: Gradle Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "17"
      - name: Generate Gradle Wrapper
        run: gradle wrapper
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Unzip for artifact
        run: |
          unzip -d artifact/ app/build/distributions/Donguri-app-*.zip
          basename artifact/* >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact/Donguri-app-*/**
